lizmap:
    build: git://github.com/geodatup/docker-lizmap-odroidC2
    restart: always
    ports:
     - "80:80"
    volumes:
     - "/home/GeoPoppy/lizmap/project:/home"
     - "/home/GeoPoppy/lizmap/project/var:/var/www/websig/lizmap/var"
     - "/home/GeoPoppy/lizmap/project/tmp:/tmp"